### ISSUE TITLE
The exampleSite directory is empty

### ISSUE THREAD

**Issue by dthuering** [open-network-infrastructure/hugo-hackatheme#1]
I wanted to have a look at the example site as suggested in the Readme but the folder is empty.

**Comment by gonzalocasas** [comment]
Here's an example site using the theme: https://github.com/make-zurich/website (live website is makezurich.ch)

**Comment by gonzalocasas** [comment]
Ok to close? (Since this is not actionable)

**Comment by dthuering** [comment]
Yes, Thank you!
